apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: mukesh2110/node-app:latest
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          value: postgres-service  # Use the PostgreSQL Service name, not localhost
        - name: DB_USER
          value: postgres
        - name: DB_PASSWORD
          value: Muke2110
        - name: DB_NAME
          value: test
        - name: DB_PORT
          value: "5432"
---
apiVersion: v1
kind: Service
metadata:
  name: node-app-service
spec:
  selector:
    app: node-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort  